org: camilaespinoza
service: api-s3

provider:
  name: aws
  runtime: python3.13
  memorySize: 256
  timeout: 20
  iam:
    role: arn:aws:iam::364506194159:role/LabRole
  environment:
    STAGE: ${opt:stage, 'dev'}  # Usar stage din√°mico

functions:
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /s3/lista-buckets
          method: get
          cors: true
  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/lista-objetos
          method: post
          cors: true
  # Nuevas funciones
  crear_bucket:
    handler: crear_bucket.lambda_handler
    events:
      - http:
          path: /s3/crear-bucket
          method: post
          cors: true
  crear_directorio:
    handler: crear_directorio.lambda_handler
    events:
      - http:
          path: /s3/crear-directorio
          method: post
          cors: true
  subir_archivo:
    handler: subir_archivo.lambda_handler
    events:
      - http:
          path: /s3/subir-archivo
          method: post
          cors: true
